# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=120, null=True)),
                ('author_name', models.CharField(max_length=120, null=True)),
                ('message', models.CharField(max_length=120)),
                ('teacher', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='thread_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField()),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(max_length=120, null=True)),
                ('author', models.CharField(max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class_data')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department_data')),
            ],
        ),
        migrations.AddField(
            model_name='message_data',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread_data'),
        ),
    ]
