# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_data',
            name='profile',
            field=models.ImageField(blank=True, default='media/profile/people.png', null=True, upload_to='media/profile'),
        ),
    ]
