# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20170205_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects_data',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
