# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20170205_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_announcements',
            name='description',
            field=models.CharField(max_length=1048, null=True),
        ),
        migrations.AlterField(
            model_name='class_assignments',
            name='description',
            field=models.CharField(max_length=1048, null=True),
        ),
    ]
