# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_data',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('fcm', models.CharField(blank=True, max_length=120, null=True)),
                ('otp', models.CharField(max_length=120, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='students_in_class_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class_data')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students_data')),
            ],
        ),
    ]
