# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170205_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_data',
            old_name='profile_iage',
            new_name='profile_image',
        ),
    ]
